name: Setup code base
description: "Setup the repo"
runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        cache: true
        go-version-file: ./go.mod
    - name: Create compilable code
      shell: bash
      run: |
        make setup
